title: Pactus blockchain
email:
source: website
description: >-
  Pactus is truly decentralized Proof-of-Stake blockchain
baseurl: ""
url: "https://www.pactus.org"

plugins:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-feed

languages: ["en"]

exclude_from_localizations: ["assets", "404.html",  "meta", "_posts", "blog"]

markdown: kramdown

paginate: 10
paginate_path: blog/page:num/

feed:
  posts_limit: 20
