name: Deploy to GitHub pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: jeffreytse/jekyll-deploy-action@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: 'pactus.org'
